language: node_js
node_js:
    - '8'
before_install:
    - npm install -g tslint --no-save
    - npm install -g firebase-tools --no-save
install:
    - npm install --no-save
    - cd functions && npm install --no-save && cd ..
script:
    - npm test
    - npm run style-check
    - npm run build
deploy:
    skip_cleanup: true
    provider: firebase
    token: "1/FGdApIEIqn6C3OKGRfv7dGdJf2WqAbV_Dp-KN9GMUWI"
    on:
        branch: master
