language: node_js
node_js:
  - '8'
after_install:
  - cd functions && npm install && cd ..
script:
  - npm test
  - npm run style-check
deploy:
  provider: firebase
  token: "1/FGdApIEIqn6C3OKGRfv7dGdJf2WqAbV_Dp-KN9GMUWI"
  on:
    branch: master
